### ISSUE TITLE
Team mentions do not work without a PAT or app token that has Organization Member read permissions  

### ISSUE THREAD

**Issue by nicknovitski** [tobyhs/codemention#23]
This is a limitation with github, so there's no code fix, but documentation explaining it might save people some time.

**Comment by tobyhs** [comment]
Hi @nicknovitski,

I opened https://github.com/tobyhs/codemention/pull/24 for this. Let me know if you think that is sufficient.

**Comment by nicknovitski** [comment]
I think that will help people, thank you. I ended up doing this: 
```yaml
- uses: tibdex/github-app-token@v2
  id: generate-token
  with:
    app_id: ${{ secrets.<the id of a github app installed in my organization with the teams:read permission > }}
    private_key: ${{ secrets.< the private key of that app > }}
- uses: tobyhs/codemention@v1.4.0
   with:
     githubToken: ${{ steps.generate-token.outputs.token }}
```
